SELECT *
FROM customer
LIMIT 20

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, sum(purchase_amount)
FROM customer
GROUP BY gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer.customer_id,customer.purchase_amount
FROM customer
WHERE (customer.discount_applied = 'Yes') 
 AND (customer.purchase_amount) > 
  (
   SELECT avg(purchase_amount)
   FROM customer
   )

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT customer.item_purchased,ROUND(avg(customer.review_rating::numeric),2) as average_review_rating
FROM customer
GROUP BY customer.item_purchased
ORDER BY avg(customer.review_rating) DESC
LIMIT 5


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT customer.shipping_type,
       round(avg(customer.purchase_amount),2) as Average_purchase_amounts
FROM customer
WHERE (customer.shipping_type = 'Express') 
   OR (customer.shipping_type = 'Standard')
GROUP BY customer.shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT customer.subscription_status,
       count(customer.customer_id) as total_customers,
	   round(avg(customer.purchase_amount),2) AS average_spend,
	   round(sum(customer.purchase_amount),2) AS total_revenue
FROM customer
GROUP BY customer.subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT customer.item_purchased,
       ROUND(COUNT(
	    CASE
	      WHEN customer.discount_applied = 'Yes'
		   THEN 1 
		   END ) * 100 
		   /
	    COUNT(customer.customer_id),2) AS discount_percentage
FROM customer
GROUP BY customer.item_purchased
ORDER BY  discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_segment AS (
 SELECT 
       CASE WHEN customer.previous_purchases = 1 THEN 'New'
            WHEN customer.previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            WHEN customer.previous_purchases > 10 THEN 'Loyal'
			END AS segment
			FROM customer
			)
 SELECT segment,COUNT(*) AS customer_count
 FROM customer_segment
 GROUP BY segment
 ORDER BY customer_count DESC


-- Q8. What are the top 3 most purchased products within each category?

WITH item_count AS (
SELECT customer.category,
       customer.item_purchased,
	   count(customer_id) as customer_count,
	   ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id)DESC) as item_rank
FROM customer
GROUP BY customer.category,customer.item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
	   customer_count
FROM item_count
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
       subscription_status,
	   COUNT (*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT 
       customer.age_group,
       sum(customer.purchase_amount) as revenue_contribution
FROM customer
GROUP BY customer.age_group
ORDER BY revenue_contribution DESC

